# Python

## Les n-uplets (tuples)
* Comme les listes sauf que l'on ne peut pas les modifier
* Défini avec des ()
* Utilisé pour regroupé une nombre connu de données : (x, y, z)
* Utilisé lorsqu'une fonction renvoie plusieurs valeurs

In [3]:
a = (1, 2, 3)
a[1] = 3

TypeError: 'tuple' object does not support item assignment

In [4]:
def ma_fonction():
    return 1, 2, 3

a, b, c = ma_fonction()

a = ma_fonction()
print(type(a))
print(a[1])

<class 'tuple'>
2


In [5]:
a, b, c = (1, 2, 5)
print(b)

2


In [6]:
()

()

In [8]:
(1,)

(1,)

## Les dictionnaires
* Conteneur (comme les listes ou tuple)
* Le contenu est indéxé par une clé qui est en général un nombre ou une chaine de caractère
* Explicit is better than implicit (paramètre ou résultat d'une expérience)
* Utilisation dans les fonctions

In [9]:
parametres = {"N":100, 'l':30, "h":50, "g":9.81}
print(parametres['N'])

for key, val in parametres.items():
    print(f'La valeur de {key} est {val}')

100
La valeur de N est 100
La valeur de l est 30
La valeur de h est 50
La valeur de g est 9.81


In [11]:
personne_1 = {"nom":"Dupont", "age":13}
personne_2 = {"nom":"Dubois", "age":34}

annuaire = [personne_1, personne_2]

for personne in annuaire : 
    print(f"{personne['nom']} a {personne['age']} ans.")
    #print('{} a {} ans'.format(personne['nom'], personne['age']))

Dupont a 13 ans.
Dubois a 34 ans.


## Les ensembles
* Comme en mathématiques : ne contient pas deux fois le même élément
* Union |, intersection &

In [20]:
s1 = {1, 3, 4}
s2 = {1, 6, 8}
print(s1|s2)
print(s1&s2)

s = "Comme en mathématiques : ne contient pas deux fois le même élément"
toutes_les_lettres = set(s.lower())
print(toutes_les_lettres)
len(toutes_les_lettres)
for lettre in toutes_les_lettres:
    print(lettre, s.count(lettre))

{1, 3, 4, 6, 8}
{1}
{'m', ' ', 'e', 'l', 'u', 'q', ':', 'ê', 't', 'c', 'p', 'f', 'n', 'd', 'h', 'o', 'i', 's', 'x', 'a', 'é'}
m 7
  11
e 9
l 2
u 2
q 1
: 1
ê 1
t 5
c 1
p 1
f 1
n 5
d 1
h 1
o 3
i 3
s 3
x 1
a 3
é 3


## Les fonctions

Nombre arbitraire d'arguments (tuple et dictionnaire)

In [24]:
def f(a, b, c):
    print(a, b, c)
    
f(1, 2, 3)
p = (2, 3)
f(1, *p)
d = {'a':1, 'c':2}
f(b=3, **d)

1 2 3
1 2 3
1 3 2


In [27]:
def f(a, *args, **kwd):
    print(a, args, kwd)

f(1, 2, 3, 4)
f(1, 2, 3, m=4, l=5)

1 (2, 3, 4) {}
1 (2, 3) {'m': 4, 'l': 5}


In [29]:
d = {'a':1, 'c':2}
f(**d)

import numpy as np

parametres_pendule = {"m":100, 'l':30, "g":9.81}    
def periode(l, g, **kwd):
    return 2*np.pi*np.sqrt(l/g)

periode(**parametres_pendule)

1 () {'c': 2}


10.987679728847352

In [25]:
print(1, 2, 3)

1 2 3


### Fonctions anonymes 
` lambda arg1, arg2 : expr`

In [30]:
(lambda a, b, c:a+b+c)(1, 2, 3)

6

In [ ]:
# integrale(f, a, b, N_step)
# integrale(lambda x: exp(-x**2), 0, 1, 100)

# Modules en Python

* Les modules sont des fichiers dont on peut importer les objets (en général des fonctions) qui y sont définis. 
* Un module peut contenir d'autre modules
* Modules standards (ex: math)

In [ ]:
from math import exp
exp(2.1)

In [ ]:
import math
math.exp(1)

In [ ]:
# Syntaxe à éviter
from math import *
sin(pi/4)

In [ ]:
# Donner un nom plus simple
# Eviter sauf si tout le monde le fait
import numpy as np

# Langage orienté objet

* Tout en Python est object
* Un objet contient des données 
* La classe d'un objet défini ce qu'est l'objet
* La classe défini des fonctions qui permettent d'utiliser les données de l'objet ou de le modifier. Ce sont des méthodes

Exemples : 
* liste, nombre complexe
* Tableaux numpy
* Oscilloscope

In [32]:
l = [5, 4, 1, 2]
l.insert(1, 'coucou') # modification de l'objet
print(l)
print(l.index(2))
z = 1 + 2J
z.real # attribut de l'objet
z.conjugate() # methode qui renvoie un nouvel objet

[5, 'coucou', 4, 1, 2]
4


(1-2j)

In [34]:
print(l.insert(2, 'bonjour'))

None


In [35]:
a = [1, 2, 3]
b = a
a.insert(0, 45)
print(b[0])

45


In [36]:
a = [1, 2, 4]
b = a
a = 'Bonjour'
print(b[0])

1


## Variables globales/locales
* Dans une fonction, une variable est soit globale soit locale
* Si on assigne un objet à une variable dans une fonction, elle est automatiquement locale
* Modifier une liste ne rend pas la liste locale
* L'instrution `global` ne doit **jamais** être utilisée (sauf cas exceptionels)

In [37]:
x = 1
def f1():
    print(x)
f1()
x = 3
f1()

1
3


In [38]:
def f2(x):
    print(x)
f2(4)

4


In [40]:
    
def f3():
    x = 4
    print(x)
f3()
x

4


3

In [41]:
x = 2   
def f4():
    print(x)
    x = 4
    print(x)
f4()

UnboundLocalError: local variable 'x' referenced before assignment

Les variables globales doivent être constantes : 
* Constantes numériques
* Autres objets : fonctions, modules, ...

In [42]:
from math import sin, pi

def ma_fonction(x):
    if x==0:
        return 1
    return sin(pi*x)/(pi*x)




# Les exceptions (erreurs)
* Il faut toujours lire et comprendre les erreurs
* En général python indique toujours l'endroit où se trouve l'erreur
* Sauf pour les "syntax error"

In [44]:
variable = 34
print(2*variable + 2)

70


In [46]:
from math import sqrt

sqrt(-1)

ValueError: math domain error

In [49]:
def f(x):
    y = 2*x
    print(x)
    

In [50]:
l = [1, 2, 4]
l(1)

TypeError: 'list' object is not callable

In [51]:
def f(x):
    print(x)
    
f[1]

TypeError: 'function' object is not subscriptable

## Créer sa propre erreur
* raise Exception('Un message')
* Ne pas utiliser print(message)
* try: except

In [52]:
# On lance une balle à la vitesse v_0 vers le haut
# Calculer le temps pour arriver au plafond de hauteur h
from math import sqrt
def temps_arrivee(h, v_0, g=9.81):
    Delta = v_0**2 - 2*g*h
    if Delta<0:
        raise Exception("La balle ne touche pas le plafond")
    return (v_0 - sqrt(Delta))/g

print(temps_arrivee(h=1, v_0=10))
print(temps_arrivee(h=1, v_0=1))

0.10545470031833197


Exception: La balle ne touche pas le plafond

In [53]:
from math import sqrt
def temps_arrivee(h, v_0, g=9.81):
    Delta = v_0**2 - 2*g*h
    try:
        return (v_0 - sqrt(Delta))/g
    except ValueError:
        raise Exception("La balle ne touche pas le plafond")
print(temps_arrivee(1, 10))
print(temps_arrivee(1, 1))

0.10545470031833197


Exception: La balle ne touche pas le plafond

# Les fichiers
* Répertoire absolu et relatif
* Chemin d'accès
* Fichier texte (c'est une chaine de caractère)
* Lecture/écriture
* Format JSON

In [54]:
!pwd
# Sous windows : c:\Users\login\

/home/pierre/Enseignement/2021/python_pour_scientifique/cours/cours2


In [55]:
filename = "/home/pierre/Enseignement/2021/python_pour_scientifique/cours/cours2/Python_et_numpy_avance.ipynb"

In [59]:
# Chemin relatif
import os
print(os.listdir('../cours1'))

['Bases de python et utilisation de numpy.ipynb', 'test_long.txt', 'test.txt', '.ipynb_checkpoints', 'test_long.npy', 'Bases de python et utilisation de numpy.pdf']


In [64]:
file = 'data/test_python.txt'
fd = open(file, 'w')
fd.write('Bonjour\n')
fd.close()

with open(file, 'a') as fd:
    fd.write('Au revoir')

In [65]:
with open(file) as fd:
    print(fd.read())

Bonjour
Au revoir


In [66]:
with open(file) as fd:
    lines = fd.readlines()
    
for line in lines:
    print(line.strip()) # strip pour enlever le \n

Bonjour
Au revoir


In [67]:
file = "../cours1/test.txt"
with open(file) as fd:
    print(fd.read())

1.151998738082691265e+00
1.106094761441734242e+00
1.064792205246391399e+00
1.162119087304531728e+00
9.478692289710572982e-01



## JSON
* Permet d'enregistrer une liste ou un dictionnaire
* Fichier lisible par un humain

In [68]:
import json

personne_1 = {"nom":"Dupont", "age":13}
personne_2 = {"nom":"Dubois", "age":34}

annuaire = [personne_1, personne_2]

file = 'test.json'
with open(file, "w") as f:
    json.dump(annuaire, f, indent=2)
    

In [69]:
with open(file) as f:
    annuaire = json.load(f)
print(annuaire)    
    


[{'nom': 'Dupont', 'age': 13}, {'nom': 'Dubois', 'age': 34}]


# Numpy

# Tableau dans la mémoire
* strides
* from numpy.lib.stride_tricks import as_strided

In [70]:
a = []
b = a
b.append(1)
a

[1]

In [71]:
a = np.arange(10)
b = a[:3]
b[0] = 10
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [72]:
a.shape

(10,)

In [74]:
a = np.linspace(0, 1, 11)
a.dtype = np.int64
a

array([                  0, 4591870180066957722, 4596373779694328218,
       4599075939470750516, 4600877379321698714, 4602678819172646912,
       4603579539098121012, 4604480259023595111, 4605380978949069210,
       4606281698874543309, 4607182418800017408])

In [75]:
b = a[::2]

In [77]:
print(a.strides)
print(b.strides)

(8,)
(16,)


In [79]:
a = np.zeros((4, 3))
a.strides

(24, 8)

In [81]:
a = np.arange(10)
a.reshape((5, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [80]:
from numpy.lib.stride_tricks import as_strided
a = np.arange(10)
b = as_strided(a, shape=((6, 5)), strides=(8, 8))
print(b)
#b.mean(axis=1)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]
 [5 6 7 8 9]]


# Tableaux nD

In [84]:
a = np.array([[1,2], [3, 4]])
# l'index est un tuple
a[0, 1]
a[(0, 1)]

2

In [85]:
x = np.random.rand(5, 5)
# Récupérer une colonne
x[:,0]

array([0.20444039, 0.61491824, 0.70563019, 0.76157881, 0.06011002])

In [86]:
# méthode reshape
x = np.random.rand(25)
x.reshape((5, 5))

array([[0.89910354, 0.70125995, 0.6941588 , 0.37258508, 0.70396985],
       [0.88415334, 0.98104865, 0.27976175, 0.61434796, 0.1310928 ],
       [0.18321393, 0.95836867, 0.34211264, 0.4090201 , 0.30691607],
       [0.19384562, 0.25635118, 0.57094225, 0.55928077, 0.46653044],
       [0.35970172, 0.25309066, 0.99839632, 0.08725984, 0.94497317]])

In [87]:
x = np.random.rand(5, 3)
x.strides

(24, 8)

In [88]:
# Attention, numpy évite de recopier la memoire
x = np.arange(10)
b = x[1::2]
b[2] = 100
x

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [89]:
x = np.arange(10)
b = x[x%2==0]
b[2] = 100
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
# meshgrid
a, b = np.meshgrid([1, 2, 3], [7, 8, 9])
print(a)
print(b)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[7 7 7]
 [8 8 8]
 [9 9 9]]


In [ ]:

# Création d'une image 2D avec meshgrid

x = linspace(-.5, .5, 100)*4*pi
y = linspace(-.5, .5, 100)*4*pi
X, Y = meshgrid(x, y)
R = sqrt(X**2 + Y**2)
imshow((sin(Y)+cos(X))*exp(-R**2/30))

# Broadcast

In [ ]:
# Si sur une dimension la taille du tableau vaut 1, alors numpy peut l'étendre
# pour qu'elle ait la même valeur que celle de l'autre tableau
x = random.rand(5, 5)
a = array([arange(5)])
print(a.shape)
x + a
x[2:4, :] = a
x

In [ ]:
x = np.arange(10)
x + 1

In [ ]:
# Il y a une syntaxe simple pour rajouter une dimension de taille 1
# C'est newaxis
a = arange(5)
b = a[np.newaxis, :]
x = random.rand(5, 5)
x[2:4, :] = b
x

In [ ]:
# Exemple : calculer une moyenne pondérée 
# Chaque ligne est un élève, chaque colonne un examen
notes = random.rand(10, 5)*20
print(notes)
coef = array([1, 4, 2, 5, 8])

In [ ]:
# Il est inutile de faire des boucles
(notes*coef[np.newaxis, :]).sum(axis=1)/np.sum(coef)

# Au delà de numpy : numba
* Calculer $\pi$ (avec une formule très très lente!!!)
$$ \frac\pi4 = \sum_i \frac{(-1)^i}{2i+1} = 1 - \frac13 + \frac 15 - \frac17 + \ldots $$


In [ ]:
def pi_python(N):
    res = 0
    coef = 1
    for i in range(N):
        res += coef/(2*i+1)
        coef = -coef
    return 4*res

%timeit pi_python(1000000) # 155 ms

def pi_np(N):
    Ti = arange(N)
    return 4*np.sum((1-2*(Ti%2))/(2*Ti+1))

%timeit pi_np(1000000) # 28.3ms

from numba import jit, int64, float64
numba_pi = jit(float64(int64))(pi_python)

@jit( float64(int64) )
def pi_python(N):
    res = 0
    coef = 1
    for i in range(N):
        res += coef/(2*i+1)
        coef = -coef
    return 4*res
%timeit numba_pi(1000000)

In [ ]:
# Numpy utilise des variables intermédiaires -> vitesse limitée par la mémoire
(a + b)*c + a
tmp1 = a + b
tmp2 = tmp1*c
res = tmp2 + a